conda env remove --name aws_neuron_mxnet_p36
conda env remove --name aws_neuron_pytorch_p36
conda env remove --name aws_neuron_tensorflow_p36
conda env remove --name chainer_p27
conda env remove --name chainer_p36
conda env remove --name mxnet_p27
conda env remove --name mxnet_p36
conda env remove --name python2
conda env remove --name python3
conda env remove --name pytorch_latest_p36
conda env remove --name pytorch_p27
conda env remove --name pytorch_p36
conda env remove --name tensorflow2_p27
conda env remove --name tensorflow2_p36
conda env remove --name tensorflow_p27
conda env remove --name tensorflow_p36
